### PR TITLE
Ndtree trainer

### PR DESCRIPTION
**Pull request by christhetree**
WIP

### CODE REVIEW

**Comment by jq** [comment]
Cool!

**Comment by jq** [comment]
@christhetree break unit test, merge master and test

**Comment by christhetree** [comment]
Thanks @jq, will have PR updated with everything by the end of today (Monday).

**Comment by christhetree** [comment]
@jq Do you want unit tests for all the private methods in NDTree for a more robust test coverage? (I can make them public in order to be tested)

**Comment by jq** [comment]
@christhetree you can make it pkg access, i.e. just remove private, then you can test it in test class, since they are in same pkg.

**Comment by jq** [comment]
@christhetree I will merge it for now since I am working on the pipeline

**Pull request merged**
