### PR TITLE
add multiscale spline train in additive model

### PR DESCRIPTION
**Pull request by deerzq**
to: @hectorgon @yolken @jq

### CODE REVIEW

**Comment by hectorgon** [comment]
Actually I was thinking if you already have additive models won't a spline + linear additive function work better than multi-scale splines?

**Comment by hectorgon** [comment]
:+1:

**Comment by deerzq** [comment]
I guess multiscale spline + linear might work better than spline + linear

**Comment by deerzq** [comment]
@jq nothing related to that test was changed, the test itself may fail ocassionally

**Pull request merged**
